### ISSUE TITLE
Queue based rate limiting under the hood

### ISSUE THREAD

**Issue by daymxn** [muxinc/mux-node-sdk#107]
Something of the likes of _[axios-rate-limit](https://github.com/aishek/axios-rate-limit)_ that conforms to the 1rps sending & 5rps retrieval API limits of mux could be a great addition.

**Comment by dylanjha** [comment]
Interesting idea, I can see how that would be valuable @NotDaymon 

Are you using this SDK to write some long-running scripts?

**Comment by NotDaymon** [comment]
> Interesting idea, I can see how that would be valuable @NotDaymon
> 
> Are you using this SDK to write some long-running scripts?

Essentially, yeah. I'm working on a streaming service for a client, and I'm utilizing mux to offload a lot of the load. I keep as much data as I can within our own local databases, so the API limits aren't too much of an issue currently. But with 1rps sending, its fairly likely I can have a situation in which two end-user moderators create assets at the same time. 

Instead of creating a new instance of Mux every time I want to play with the API, I currently have a constant instance that's "shared" across resources. So they import the shared instance, and utilize that instead. This way, I can facilitate rate limits within Mux and axios directly, instead of having to modify all my Mux references to instead be queue based calls for a custom object or alternative library.

**Comment by dylanjha** [comment]
We're considering this kind of functionality out of scope for an SDK like this that wraps the API endpoints. It's probably better implemented with the help of an external library (like heapify, the one linked). There's a number of utilities that can do this sort of thing.
