### ISSUE TITLE
Webhooks: ERROR [ExceptionsHandler] No signatures found matching the expected signature for payload.

### ISSUE THREAD

**Issue by foureight84** [muxinc/mux-node-sdk#309]
I'm currently using NestJs. Loading mux-node using require instead of import since that's currently not working with library v7.3.1.

- rawBody is a buffer
- mux-signature looks something like this: `t=1691820663,v1=a07260bd9b5048958fb78018ac6ac69241a2ca763f234565d52ed560909a2edc`
- and the secret used matched with what's in the dashboard for the registered webhook url

webhook controller
```Typescript
import { Request } from 'express';
import {
  Body,
  Controller,
  Headers,
  HttpCode,
  HttpStatus,
  Post,
  RawBodyRequest,
  Req,
} from '@nestjs/common';


...

@Post('mux')
  @HttpCode(HttpStatus.OK)
  @ApiCreatedResponse({
    description: 'Mux webhook received',
  })
  handleMux(
    @Body() dto,
    @Req() req: RawBodyRequest<Request>,
    @Headers('mux-signature') muxSignature: string,
  ) {
    return this.webhooksService.handleMux(dto, req, muxSignature);
  }

```

webhook service
```Typescript
import { Injectable, RawBodyRequest } from '@nestjs/common';
const Mux = require('@mux/mux-node');
import { Request } from 'express';

...

handleMux(
    dto: any,
    req: RawBodyRequest<Request>,
    muxSignature: string,
  ) {
    console.log(
      dto,
      muxSignature,
      this.configService.get('MUX_WEBHOOK_SECRET'),
    );

    const { rawBody } = req;
    const verified = Mux.Webhooks.verifyHeader(
      rawBody,
      muxSignature,
      this.configService.get('MUX_WEBHOOK_SECRET'),
    );

    console.log(verified);
  }

```
Error:
```syslog
[Nest] 135  - 08/11/2023, 11:08:52 PM   ERROR [ExceptionsHandler] No signatures found matching the expected signature for payload.
Error: No signatures found matching the expected signature for payload.
    at Function.verify (/kenko/node_modules/@mux/mux-node/src/webhooks/resources/verify_header.ts:113:13)
    at Function.verifyHeader (/kenko/node_modules/@mux/mux-node/src/webhooks/webhooks.ts:41:25)
    at WebhookService.handleMux (/kenko/src/webhook/webhook.service.ts:28:35)
    at WebhookController.handleMux (/kenko/src/webhook/webhook.controller.ts:32:33)
    at /kenko/node_modules/@nestjs/core/router/router-execution-context.js:38:29
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at /kenko/node_modules/@nestjs/core/router/router-execution-context.js:46:28
    at /kenko/node_modules/@nestjs/core/router/router-proxy.js:9:17
```

**Comment by dylanjha** [comment]
Hi @foureight84 this is going to be a bit tough to debug regarding the secrets and things.

We know this functionality does work, we're using [it on stream.new](https://github.com/muxinc/stream.new/blob/main/pages/api/webhooks/mux.ts#L11-L15)

The most common place where folks get caught up is that the `rawBody` is not _actually_ the raw body (many frameworks will parse the rawBody into JSON, for example). From your code snippet it looks like you're handling that correctly, but could you double (or triple) check that it is in-fact the raw body.

Could you also try passing in the rawBody as a string instead of a buffer?

If none of that works, I think the best next steps here we would be if you could set up a fresh minimal Github repo with a nest app that reproduces the issue so we can debug.

**Comment by foureight84** [comment]
Will do and I'll follow up with the results. Thanks @dylanjha

**Comment by foureight84** [comment]
An oversight on my end. I mistook the RawBodyRequest object type as being the raw body itself. The object contains a 'rawBody' buffer that I needed to use instead of the entire object. I can confirm that it works in either buffer or string form.
