### ISSUE TITLE
Property 'DeliveryUsage' does not exist on type 'Video'

### ISSUE THREAD

**Issue by nwaughachukwuma** [muxinc/mux-node-sdk#82]
> Property 'DeliveryUsage' does not exist on type 'Video'

I get the above error when I try to get the delivery usage for a video by doing

```ts
const { Video } = new Mux(accessToken, secret);

Video.DeliveryUsage.list({timeframe: [startTime, endTime]}); // <--- linter picks the Error here
```

**Comment by GeneticGenesis** [comment]
Thanks @nwaughachukwuma, we have a PR open that should fix this #81 

It should be out in the next couple of days. Thanks!

**Comment by nwaughachukwuma** [comment]
Ok @GeneticGenesis, thanks!

**Comment by nwaughachukwuma** [comment]
Please see this: https://github.com/muxinc/mux-node-sdk/pull/81/files#r541002749

**Comment by nwaughachukwuma** [comment]
Which is

> @GeneticGenesis is there going to be a breaking change [here](https://github.com/muxinc/mux-node-sdk/blob/6c77897333694c25735c9f775ccef6d6764e81cf/types/mux.d.ts#L155)? We were are currently handling the response with shape:
> 
> ```ts
>  Promise<{
>   total_row_count: number
>   timeframe: number[]
>   page: number
>   limit: number
>   data: Array<DeliveryReport>
> }>
> ```
> 
> but it's looking like it's going to change here.

Which is the same as specified here: https://docs.mux.com/reference#delivery-usage

**Comment by dylanjha** [comment]
@nwaughachukwuma 

This node library (for video routes) automatically plucks off the "data" key of the response. For example:

```js
const assets = await Video.Assets.list();
```

Notice that the return value is the array itself (the `data` key on the raw response) 

similarly, with DeliveryUsage:

```js
const deliveryRecords = await Video.DeliveryUsage.list({timeframe: [startTime, endTime]});

// deliveryRecords is an array
// [
//  {
//    delivered_seconds: 2356.509245999994,
//    created_at: '1596570530',
//    asset_state: 'ready',
//    asset_id: 'K9tQVTjnvKVUwE3Q2bsWxFinrTHSei01Y',
//    asset_duration: 16.750067
//  },
//  {
//    passthrough: '4d38fa85-228c-4dcf-82c2-b521d2db44cf',
//    delivered_seconds: 275,
//    created_at: '1601529495',
//    asset_state: 'ready',
//    asset_id: 'WrcW4EG1p01wWV005dEZ9DbMs6IcwyyhF02',
//    asset_duration: 289.5
//  }
// ]
```

I just tested this out, you mentioned that you are defining this as the response shape. It doesn't look like that lines up with the value returned by the function.

```js
 Promise<{
  total_row_count: number
  timeframe: number[]
  page: number
  limit: number
  data: Array<DeliveryReport>
}>
```

As a side note: I think DeliveryUsage is perhaps the only video API route where automatically plucking the data key is inconvenient. For all the rest of the video routes it makes things easier because that's always the object you're dealing with but for this one particular route I can see where you would need to access those extra keys. There is a little bit of a workaround with the [request and response events](https://github.com/muxinc/mux-node-sdk#request-and-response-events)

**Comment by nwaughachukwuma** [comment]
Ok @dylanjha, thanks for clarifying.
