### ISSUE TITLE
invalid parameter when adding a token to a m3u8 url

### ISSUE THREAD

**Issue by BjMrq** [muxinc/mux-node-sdk#84]
Hello!
I am using ```"@mux/mux-node": "^3.1.0"```

I am able to get a livestream and an assets video playback id just fine, but when I add a token query parameters has shown in the documentation
```js
const token = Mux.JWT.sign('some-playback-id');
// https://stream.mux.com/some-playback-id.m3u8?token=${token}
```
(request then looks like this ```https://stream.mux.com/jqSQn4Vq3SmbRxGj9cZLEFJB7Eb00015jbYa3EY9dQE.m3u8?token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IlptZ....``

I get a the following error
```
{error: {messages: ["Invalid Parameters"], type: "invalid_parameters"}}
```

**Comment by dylanjha** [comment]
Hi @BjMrq - this looks like it might be an issue with the playback ID itself. Would you mind reaching out to help@mux.com or using the intercom chat bubble in the web application so we can take a look!

**Comment by BjMrq** [comment]
Hi @dylanjha thanks for helping, I intentionally put a random payback id.

**Comment by BjMrq** [comment]
Here is a failling request wuith valid id 

```
https://stream.mux.com/OzJrJ431iiyW702b4iceBClDHdRe01giL4lTcOIbxb98g.m3u8?token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IlptZ3QwMW5nYWFqcWE3WWNrcEkwMkZETzAySDAyVHNtRXMxY0Z3Y1lwRzk2Q0F3In0.eyJleHAiOjE2MDg1NzQxNDUsImF1ZCI6InYiLCJzdWIiOiJPekpySjQzMWlpeVc3MDJiNGlj..
```

**Comment by dylanjha** [comment]
Thanks for the details @BjMrq. This is a support issue, not something specific to this particular library. If you don't mind, I would still like to direct the conversation to support channels.

Since we're here though, it looks like this playback ID (`OzJrJ431iiyW702b4iceBClDHdRe01giL4lTcOIbxb98g`) might be a `public` playback ID. In order to use tokens, make sure that you are dealing with a `signed` playback ID: https://docs.mux.com/docs/security-signed-urls

It's an intentional design decision that `token=` cannot be used successfully with `public` playback IDs (we wouldn't want users to be using tokens and give themselves the illusion of security, when in fact their playback ID is public).

If there is an issue with this particular SDK, we can open this back up, but for now let's direct this towards Mux support (help@mux.com or the intercom chat bubble in the web application and we'll be happy to help). Thanks!

**Comment by BjMrq** [comment]
Thanks for the clarifications @dylanjha !
