### ISSUE TITLE
How to get the storage bucket for my mux file

### ISSUE THREAD

**Issue by nwaughachukwuma** [muxinc/mux-node-sdk#98]
Hi, I use mux for video streaming and have been running direct uploads from the client browsers to Mux using [Upchunk](https://github.com/muxinc/upchunk) until recently when I decided to revamp the flow.

So now, I upload to a Google Storage bucket before using Mux PULL-BASED approach to create an asset with a reference to the file on GCS as input. And it works really seamless.

```ts
// Create an asset
const asset = await Video.Assets.create({
  input: 'https://storage.googleapis.com/muxdemofiles/mux-video-intro.mp4',
});
```

Now I am trying to sync my files from Mux to my GCS bucket but don't want to use Google storage transfer service. I'm hoping that I can get a handle for my files on Mux storage bucket, GCS or S3, and use `GCP's gsutil` to copy the files to my storage bucket. Something like the this:

```cmd
gsutil -h "Content-Type:video/mp4" -m cp gs://stream.mux.com/file-uuid/high.mp4 gs://mux-migration/video-files/-6mERHzSS-
```

**Comment by dylanjha** [comment]
Hi @nwaughachukwuma ,

Thanks for the question. I think I see what you're getting at.

You can definitely get a handle on your Mux videos in mp4 format either with [mp4-support](https://docs.mux.com/reference#update-mp4-support) or [master-access](https://docs.mux.com/reference#update-master-access).

As for the underlying URL the static rendition mp4s are `https://stream.mux.com....` and the master access mp4 is `https://master.mux.com...`

The protocol for retrieving those files is `https://`, you wouldn't be able to use `gs://` URLs to access them. After some poking around I think `gsutil cp` can be used in conjunction with `curl`'ing a remote URL so that might be your best bet. Something like this might work (although I haven't tried it):

```
curl https://master.mux.com... | gsutil cp - gs://mux-migration/video-files...
```

Does that answer your question?

**Comment by nwaughachukwuma** [comment]
Hi @dylanjha,

Yes it works and In fact, I have copied/uploaded a couple of files using this approach. The thing is that I don't want to run it through my system since I'm dealing with a lot of medium to heavy video files

**Comment by dylanjha** [comment]
Got it, so you want to take the files out of Mux and put them in your Google storage bucket. Is your intention to avoid the ingress cost of that?

If so, I'm afraid that's unavoidable. The only APIs available to get mp4s out of Mux is with the `https://` URLs.

How many Mux assets are we talking about here? I'll reach out directly to you via email to learn more about your specific situation.

**Comment by nwaughachukwuma** [comment]
Ok @dylanjha I'll respond to your email. Thanks
